site_name: Модуль Контур.Фокус для 1С
nav:
  - Описание: index.md
  - О модуле:
    - Конфигурации: conf.md
  - Возможности:
    - Администрирование списков проверки:
      - Панель администрирования списков проверки: Auto/list_admin/Панель Администрирование списков проверки.md
      - Создание списка проверки для пользователя: Auto/list_admin/Администрирование списков проверки.md
    - Блокировка операций: 
      - Настройка: Auto/Возможнсть запретить выполение операций по стоп-факторам.md
      - Исключения: Auto/Настройка исключений блокировки.md
      - Пример: Auto/Блокировка операций.md
theme:
  name: material
  language: ru
  logo: assets/images/logo.png
  favicon: assets/images/Icon.ico
  palette:
    primary: Green
    accent: indigo
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
