site_name: Модуль Контур.Фокус для 1С
nav:
  - Описание: index.md
  - О модуле:
    - Конфигурации: conf.md
  - Возможности:
    - Блокировка операций: 
      - Настройка: Auto/Возможнсть запретить выполение операций по стоп-факторам.md
      - Исключения: Auto/Блокировка операций.md
      - Пример: Auto/Настройка исключений блокировки.md
theme:
  name: material
  language: ru
  logo: assets/images/logo.png
  favicon: assets/images/icon.ico
  palette:
    primary: Green
    accent: indigo
